services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url-shortener-app
    ports:
      - "8080:80"
    environment:
      APP_NAME: "URL Shortener"
      APP_ENV: production
      APP_KEY: "${APP_KEY}"
      APP_DEBUG: "false"
      APP_URL: "http://localhost:8080"
      LOG_CHANNEL: stderr
      LOG_LEVEL: error
      DB_CONNECTION: pgsql
      DB_HOST: postgresql-url
      DB_PORT: 5432
      DB_DATABASE: url_shortener
      DB_USERNAME: user
      DB_PASSWORD: password
      SESSION_DRIVER: database
      QUEUE_CONNECTION: redis
      CACHE_STORE: redis
      REDIS_HOST: redis-url
      REDIS_PORT: 6379
    depends_on:
      - postgresql-url
      - redis-url
    restart: unless-stopped

  redis-url:
    image: redis:latest
    container_name: redis-url
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  postgresql-url:
    image: postgres:18-alpine
    container_name: postgresql-url
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: url_shortener
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  mailpit-url:
    image: axllent/mailpit
    container_name: mailpit-url
    restart: unless-stopped
    volumes:
      - mailpit-data:/data
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  redis-data:
  postgresql-data:
  mailpit-data:
